create table if not exists planning_sessions (
  id bigint generated by default as identity primary key,
  name text,
  created_at timestamptz
);

create table if not exists participants (
  id bigint generated by default as identity primary key,
  name text,
  vote bigint,
  planning_session_id bigint references public.planning_sessions
);

begin;
  drop publication if exists supabase_realtime; 
  create publication supabase_realtime;
commit;

alter publication supabase_realtime add table public.planning_sessions;
alter publication supabase_realtime add table public.participants;
