image: cirrusci/flutter:2.10.3

before_script:
  - flutter config --enable-web
  - flutter pub get

pages:
  stage: deploy
  script:
    - flutter build web --dart-define="SUPABASE_URL=$SUPABASE_URL" --dart-define="SUPABASE_PUB_KEY=$SUPABASE_PUB_KEY"
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - main
