image: cirrusci/flutter:2.10.3

before_script:
  - chmod +x ./setup_env.sh
  - ./setup_env.sh
  - flutter config --enable-web
  - flutter pub get

pages:
  stage: deploy
  script:
    - flutter build web
    - echo -e "<script>(function () {document.write('<base href=\"' + document.location.pathname + '\" />');}());</script>\n$(cat build/web/index.html)" > build/web/index.html
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - main
