name: planning_poker
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  supabase: ^0.3.1+1
  shared_preferences: ^2.0.13
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.0.0

flutter:
  assets:
    - .env

  uses-material-design: true
